### ISSUE TITLE
Hotspot not enabled on Android Nougat and Oreo

### ISSUE THREAD

**Issue by niteshkhatri** [Sriharia/share-them#4]
Hi Sriharia,

First of all thank you for such an amazing piece of code. Your project helped me a lot in one of my Project. However, I am having some issue on Android Nougat and Oreo devices. I am not able to enable the Hotspot on Android N and O. Kindly help me out.

Shall I do some extra coding for the same?

**Comment by uethkt-TeamCupcake** [comment]
@Sriharia shi
please help

**Comment by karuppiah7890** [comment]
Nitesh, you could try it and send a PR if you know how to do it. That's how
OSS works :)

**Comment by ricky1550** [comment]
@Sriharia Can you please help as this is not working in Android N .

**Comment by Gowthaman-Uohamctechnologies** [comment]
@Sriharia waiting for next update Can you please help as this is not working in Android N ....when can we get v2 please tell me sir.......

**Comment by Gowthaman-Uohamctechnologies** [comment]
@Sriharia How to sent file with particular receiver.....please help me sir...

**Comment by Gowthaman-Uohamctechnologies** [comment]
@ricky1550 it's working in Android N...I test please check properly..........

**Comment by Sriharia** [comment]
Hi @niteshkhatri @ricky1550 added Oreo Support in 3745da54c963c2a9e996db097e68921bee206e90
